### ISSUE TITLE
FATAL: database "google_smtp_sample_development" does not exist

### ISSUE THREAD

**Issue by naelah** [hudadiaz/rais-google-smtp-example#1]
<img width="1019" alt="screen shot 2017-02-10 at 1 11 00 pm" src="https://cloud.githubusercontent.com/assets/15151318/22814984/f0e0a4a6-ef92-11e6-9e05-9ef602765113.png">

**Comment by zaidhuda** [comment]
@naelah have you setup the database? You need to run `rake db:setup`.

**Comment by naelah** [comment]
Work now thanks.
